version:  "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  node-app:
    build:  .
    environment:
      - PORT=7000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis

volumes:
  mongo-db: